INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE) VALUES (1, 'jss', '1234', 'jss', 'jss@boraseoksoon.net', CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE) VALUES (2, 'kbr', '1234', 'kbr', 'kbr@boraseoksoon.net', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (ID, TITLE, WRITER_ID, CREATED_DATE, CONTENTS, COUNT_OF_ANSWER) VALUES (1, '장석순이 쓴 글 입니다.', 1, CURRENT_TIMESTAMP(), '나무아비타타타타타타라불', 0);
INSERT INTO QUESTION (ID, TITLE, WRITER_ID, CREATED_DATE, CONTENTS, COUNT_OF_ANSWER) VALUES (2, 'I am English guy.', 2, CURRENT_TIMESTAMP(), 'You know what time it is?', 0);
